// ===================== i18n (PT / EN) =====================
// Todo o conteúdo textual do site. Editar aqui troca o site inteiro.

export type Lang = "pt" | "en";

export const LANGS: Lang[] = ["pt", "en"];

export const CONTENT = {
  pt: {
    nav: { home: "Início", about: "Sobre", skills: "Skills", projects: "Projetos", contact: "Contato", cta: "Vamos conversar" },
    hero: {
      taglineLead: "Construo aplicações full-stack",
      taglineMain: "do back ao front,",
      taglineEm: "do conceito ao deploy.",
      loc1: "Indaiatuba",
      loc2: "Brasil · Disponível",
      role1: "Full-Stack Dev",
      role2: "& Engenheiro",
      available: "Disponível para projetos",
    },
    about: {
      label: "Sobre",
      heading: "Estratégia e Código",
      sub: "Unindo visão de negócios e engenharia de software para entregar soluções completas.",
      // Marque as palavras-chave a destacar com **asteriscos**.
      intro: [
        "Trabalho na área de tecnologia há **mais de 5 anos**, atualmente como **desenvolvedor**, construindo **aplicações web e mobile** do zero à entrega final do produto. Meu trabalho vai desde a arquitetura de **APIs robustas** em **C#/.NET** até a criação de interfaces modernas e performáticas com **React**, **Next.js** e **Astro**.",
        "Já construí e migrei sistemas utilizados por **mais de 6.000 usuários**, aplicando **Clean Architecture**, **TypeScript** e bancos de dados como **PostgreSQL** e **SQL Server**. Seja no ambiente corporativo, em projetos próprios ou freelances, gerencio **todo o ciclo de vida do software** para garantir soluções **escaláveis** e de **alta usabilidade**.",
        "Sou formado em **Administração de Empresas** e curso **Análise e Desenvolvimento de Sistemas** (FATEC) — uma combinação que me proporciona uma forte **visão estratégica**. Acredito que entender a raiz do problema do negócio vem antes de escrever a primeira linha de código.",
      ],
      statLabel: "projetos entregues",
      statSuffix: "+",
      available: "Disponível agora",
      chips: ["5+ anos na área de tecnologia", "Full stack", "Disponível para projetos e oportunidades"],
      cards: {
        locLabel: "Localização",
        locValue: "Indaiatuba, São Paulo · Brasil",
        roleLabel: "Cargo atual",
        // TODO: trocar depois para "Freelancer · Disponível para projetos"
        roleValue: "Full-Stack Developer",
        roleSub: "ACSN",
        eduLabel: "Formação",
        edu: [
          { school: "FATEC Indaiatuba", detail: "Análise e Desenvolvimento de Sistemas (último ano)" },
          { school: "Universidade Anhembi Morumbi", detail: "Administração de Empresas" },
        ],
        langLabel: "Idiomas",
        lang: [
          { name: "Português", level: "Nativo" },
          { name: "Inglês", level: "Avançado · TOEIC" },
        ],
      },
    },
    skills: {
      label: "Skills",
      heading: "Ferramentas do dia a dia",
      sub: "Do front interativo ao back-end escalável — a stack com que trabalho no dia a dia.",
      cats: { backend: "Backend", frontend: "Frontend", mobile: "Mobile", database: "Banco de dados", devops: "DevOps", arch: "Arquitetura", lang: "Linguagem", cloud: "Cloud" },
      showAll: "Tecnologias que tive pouco contato",
      showLess: "Ver menos",
    },
    projects: {
      label: "Projetos",
      heading: "Construindo projetos de valor",
      sub: "Plataformas e produtos reais, do conceito ao deploy.",
      featured: "Em destaque",
      live: "Ver ao vivo",
      code: "Código",
      countLabel: "projetos",
    },
    contact: {
      label: "Contato",
      heading: "Vamos construir algo",
      sub: "Disponível para projetos freelance e oportunidades. Manda uma mensagem ou agenda uma conversa rápida.",
      formLabel: "Me conte sua ideia",
      fName: "Nome",
      fEmail: "E-mail",
      fMessage: "Conta um pouco sobre o projeto…",
      fSend: "Enviar mensagem",
      fSending: "Enviando…",
      fSent: "Mensagem enviada",
      fSentSub: "Obrigado! Respondo o mais rápido possível.",
      fAgain: "Enviar outra",
      fError: "Algo deu errado. Tenta de novo ou manda um e-mail direto.",
      directLabel: "Canais diretos",
      copy: "copiar",
      copied: "copiado",
      whatsapp: "WhatsApp",
      cv: "Baixar CV",
      orBook: "Prefere conversar?",
      book: "Ver horários",
      availLine: "Aberto a projetos e oportunidades.",
      statusAvailable: "Disponível",
      replyTime: "respondo em ~24h",
      waGreeting: "Olá, Pedro! Vim pelo seu portfólio.",
    },
    footer: { rights: "© 2026 Pedro Tozaki" },
  },
  en: {
    nav: { home: "Home", about: "About", skills: "Skills", projects: "Projects", contact: "Contact", cta: "Let's talk" },
    hero: {
      taglineLead: "I build full-stack applications",
      taglineMain: "back to front,",
      taglineEm: "concept to deploy.",
      loc1: "Indaiatuba",
      loc2: "Brazil · Available",
      role1: "Full-Stack Dev",
      role2: "& Engineer",
      available: "Available for work",
    },
    about: {
      label: "About",
      heading: "Strategy & Code",
      sub: "Bridging business strategy and software engineering to deliver end-to-end solutions.",
      // Mark the keywords to highlight with **asterisks**.
      intro: [
        "I've worked in tech for **5+ years**, currently as a **developer**, building **web and mobile applications** from scratch to final delivery. My work ranges from architecting **robust APIs** in **C#/.NET** to crafting modern, high-performance interfaces with **React**, **Next.js** and **Astro**.",
        "I've built and migrated systems used by **6,000+ users**, applying **Clean Architecture**, **TypeScript** and databases like **PostgreSQL** and **SQL Server**. Whether in a corporate environment, my own projects or freelance work, I manage the **entire software lifecycle** to deliver **scalable** solutions with **high usability**.",
        "I hold a degree in **Business Administration** and am studying **Systems Analysis and Development** (FATEC) — a combination that gives me strong **strategic vision**. I believe understanding the root of the business problem comes before writing the first line of code.",
      ],
      statLabel: "projects shipped",
      statSuffix: "+",
      available: "Available now",
      chips: ["5+ years in tech", "Full stack", "Available for projects and opportunities"],
      cards: {
        locLabel: "Location",
        locValue: "Indaiatuba, São Paulo · Brazil",
        roleLabel: "Current role",
        // TODO: trocar depois para "Freelancer · Disponível para projetos"
        roleValue: "Full-Stack Developer",
        roleSub: "ACSN",
        eduLabel: "Education",
        edu: [
          { school: "FATEC Indaiatuba", detail: "Systems Analysis and Development (final year)" },
          { school: "Universidade Anhembi Morumbi", detail: "Business Administration" },
        ],
        langLabel: "Languages",
        lang: [
          { name: "Portuguese", level: "Native" },
          { name: "English", level: "Advanced · TOEIC" },
        ],
      },
    },
    skills: {
      label: "Skills",
      heading: "My daily toolkit",
      sub: "From interactive front-ends to scalable back-end services — the stack I work with day to day.",
      cats: { backend: "Backend", frontend: "Frontend", mobile: "Mobile", database: "Database", devops: "DevOps", arch: "Architecture", lang: "Language", cloud: "Cloud" },
      showAll: "Less-used technologies",
      showLess: "Show less",
    },
    projects: {
      label: "Projects",
      heading: "Building valuable projects",
      sub: "Real platforms and products, from concept to deploy.",
      featured: "Featured",
      live: "Live site",
      code: "Code",
      countLabel: "projects",
    },
    contact: {
      label: "Contact",
      heading: "Let's build something",
      sub: "Available for freelance projects and opportunities. Send a message or book a quick call.",
      formLabel: "Tell me your idea",
      fName: "Name",
      fEmail: "Email",
      fMessage: "Tell me a bit about the project…",
      fSend: "Send message",
      fSending: "Sending…",
      fSent: "Message sent",
      fSentSub: "Thanks! I'll get back to you as soon as possible.",
      fAgain: "Send another",
      fError: "Something went wrong. Try again or email me directly.",
      directLabel: "Direct channels",
      copy: "copy",
      copied: "copied",
      whatsapp: "WhatsApp",
      cv: "Download CV",
      orBook: "Prefer to talk?",
      book: "View availability",
      availLine: "Open to projects and opportunities.",
      statusAvailable: "Available",
      replyTime: "replies in ~24h",
      waGreeting: "Hi Pedro! I came from your portfolio.",
    },
    footer: { rights: "© 2026 Pedro Tozaki" },
  },
} as const;

export type Dict = (typeof CONTENT)["pt"];
